language: objective-c
osx_image: xcode8

install: 
  - git clone https://github.com/Electrode-iOS/ELFoundation.git ../ELFoundation -b swift2.3
script:
   - xctool -project ELLocation.xcodeproj -scheme ELLocation -sdk iphonesimulator build test
