language: objective-c
osx_image: xcode7.3

install: 
  - git clone https://github.com/Electrode-iOS/ELFoundation.git ../ELFoundation
script:
   - xctool -project ELLocation.xcodeproj -scheme ELLocation -sdk iphonesimulator build test
