language: objective-c
osx_image: xcode7.2

install: 
  - git clone https://github.com/TheHolyGrail/ELFoundation.git ../ELFoundation
script:
   - xctool -project ELLocation.xcodeproj -scheme ELLocation -sdk iphonesimulator build test
